version: '3.3'

services:
  db:
    image: mysql:8.0.30
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./scripts:/scripts

  adonis_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis_app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: flashcards
    depends_on:
      - db
    ports:
      - "3333:3333"
    volumes:
      - .:/app

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80

volumes:
  dbdata:
